{"name": "test_create_article", "status": "broken", "statusDetails": {"message": "AttributeError: 'function' object has no attribute 'wd'", "trace": "tp = <class 'AttributeError'>, value = None, tb = None\n\n    def reraise(tp, value, tb=None):\n        try:\n            if value is None:\n                value = tp()\n            if value.__traceback__ is not tb:\n                raise value.with_traceback(tb)\n>           raise value\n\n/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/six.py:693: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/six.py:693: in reraise\n    raise value\n/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/six.py:693: in reraise\n    raise value\n/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/allure_commons/_allure.py:169: in __call__\n    return self._fixture_function(*args, **kwargs)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\n    def fin():\n>       driver = app.wd\nE       AttributeError: 'function' object has no attribute 'wd'\n\n../conftest.py:37: AttributeError"}, "attachments": [{"name": "stdout", "source": "d1b75285-8e89-4b5e-a5e2-f434d25bf724-attachment.txt", "type": "text/plain"}], "start": 1559919066327, "stop": 1559919072063, "uuid": "50a64b0a-39b3-412e-a7e9-981914ed55d0", "historyId": "12f058da07a5933658563feaed03630d", "fullName": "tests.test#test_create_article", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test"}, {"name": "host", "value": "Work-Mac-Mini.local"}, {"name": "thread", "value": "90364-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test"}]}