{"uuid": "fc82255c-8e94-4b0a-9483-e1fbc90064e8", "children": ["861f8ecc-f416-473c-bf1b-4c30d1fc5d77"], "befores": [{"name": "take_screenshot_when_failure", "status": "passed", "start": 1559914952302, "stop": 1559914952302}], "afters": [{"name": "take_screenshot_when_failure::1", "status": "passed", "start": 1559914956689, "stop": 1559914956689}, {"name": "take_screenshot_when_failure::tear_down", "status": "broken", "statusDetails": {"message": "AttributeError: 'Function' object has no attribute 'rep_call'\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/allure_commons/_allure.py\", line 169, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/Users/ace/Documents/GitHub/epam_ta/pom/conftest.py\", line 25, in tear_down\n    if request.node.rep_call.failed:\n"}, "start": 1559914956690, "stop": 1559914956690}], "start": 1559914952302, "stop": 1559914956690}